---
- name: Apply the Zcash Gitian builder role.
  become: yes
  hosts: localhost:zcash-build
  vars:
    zcash_git_repo_url: "{{ lookup('env','ZCASH_GIT_REPO_URL') }}"
    zcash_version: "{{ lookup('env','ZCASH_VERSION') }}"
    git_name: "{{ lookup('env','GIT_NAME') }}"
    git_email: "{{ lookup('env','GIT_EMAIL') }}"
    gpg_key_name: "{{ lookup('env','GPG_KEY_NAME') }}"
    gpg_key_id: "{{ lookup('env','GPG_KEY_ID') }}"
  roles:
    - role: common
      tags: common
    - role: gitian
      tags: gitian
